name: Building and Uploading Release
on:
  push:
    branches: release

jobs:
  create_release: 
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release_step.outputs.upload_url }}
    steps:
      - name: Creating Release
        id: create_release_step
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
        with:
          tag_name: v31
          release_name: Release v31

  linux-build:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Setting up Node
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
      
      # Installing Dependencies
      - name: Installing Dependencies
        run: npm ci

      # Building the linux package
      - name: Build Package
        run: npm run package-linux

      - name: Uploading ASAR
        id: upload_asar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./release-builds/Zeno-linux-x64/resources/app.asar
          asset_name: app.asar
          asset_content_type: application/octet-stream
      
      - name: Compressing Build
        run: |
            cd release-builds
            zip -r linux-v31.zip Zeno-linux-x64
      
      - name: Uploading ZIP
        id: upload_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./release-builds/linux-v31.zip
          asset_name: linux-v31.zip
          asset_content_type: application/zip

  windows-build:
    needs: create_release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      # Setting up Node
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
      
      # Installing Dependencies
      - name: Installing Dependencies
        run: npm ci

      # Building the windows package
      - name: Build Package
        run: npm run package-win

      - name: Compressing Build
        id: compressing-build
        run: |
          cd release-builds
          Compress-Archive -Path ./Zeno-win32-x64 -DestinationPath ./win32-v31.zip
      
      # Uploading a Release file
      - name: Uploading ZIP
        id: upload_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./release-builds/win32-v31.zip
          asset_name: win32-v31.zip
          asset_content_type: application/zip

  macos-build:
    needs: create_release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      # Setting up Node
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
      
      # Installing Dependencies
      - name: Installing Dependencies
        run: npm ci

      # Building the mac package
      - name: Build Package
        run: npm run package-mac

      # Making a .zip file for the release folder
      - name: Compressing Build
        id: compressing-build
        run: |
          cd release-builds
          zip -r darwin-v31.zip zeno-darwin-x64


      # Uploading a Release file
      - name: Uploading ZIP
        id: upload_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./release-builds/darwin-v31.zip
          asset_name: darwin-v31.zip
          asset_content_type: application/zip